title: Maelstrom
url: "http://acg.github.com"
description: "A gradual and wondrous descent into the vortex of code, augmented, in the due course of things, by various other bits of whirling garbage."
lang: en-us

author:
  name: Alan
  email: alangrow+maelstrom@gmail.com
  disqus: alangrow

safe:        false
auto:        false
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

